services:
  backend:
    container_name: game_back
    build: ./
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    networks:
      - net

  postgres:
    container_name: game_posetgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "game3"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "123"
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data/postgres
    networks:
      - net


networks:
  net:
    driver: bridge

volumes:
  postgres:
