"""model player position

Revision ID: 84876a5d3540
Revises: 9a723d75d51d
Create Date: 2025-09-24 22:30:46.206913

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "84876a5d3540"
down_revision: Union[str, Sequence[str], None] = "9a723d75d51d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("x", sa.Integer(), nullable=True))
    op.add_column("users", sa.Column("y", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "y")
    op.drop_column("users", "x")
    # ### end Alembic commands ###
